%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera1.fx: 746.2463540682126
Camera1.fy: 750.2202098997767
Camera1.cx: 971.6589299894808
Camera1.cy: 514.5994408429885
